// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dice.proto

package hxgm30.dice.pb.api;

public interface DiceRollOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.DiceRoll)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 result = 1;</code>
   * @return The result.
   */
  int getResult();
}
