// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dice.proto

package hxgm30.dice.pb.api;

public interface DiceRollsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.DiceRolls)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .api.DiceRoll results = 1;</code>
   */
  java.util.List<hxgm30.dice.pb.api.DiceRoll> 
      getResultsList();
  /**
   * <code>repeated .api.DiceRoll results = 1;</code>
   */
  hxgm30.dice.pb.api.DiceRoll getResults(int index);
  /**
   * <code>repeated .api.DiceRoll results = 1;</code>
   */
  int getResultsCount();
  /**
   * <code>repeated .api.DiceRoll results = 1;</code>
   */
  java.util.List<? extends hxgm30.dice.pb.api.DiceRollOrBuilder> 
      getResultsOrBuilderList();
  /**
   * <code>repeated .api.DiceRoll results = 1;</code>
   */
  hxgm30.dice.pb.api.DiceRollOrBuilder getResultsOrBuilder(
      int index);
}
