// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dice.proto

package hxgm30.dice.pb.api;

public final class DiceAPIProto {
  private DiceAPIProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_PingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_PingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_PingReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_PingReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_VersionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_VersionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_VersionReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_VersionReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ndice.proto\022\003api\"\033\n\013PingRequest\022\014\n\004data" +
      "\030\001 \001(\t\"\031\n\tPingReply\022\014\n\004data\030\001 \001(\t\"\036\n\016Ver" +
      "sionRequest\022\014\n\004data\030\001 \001(\t\"l\n\014VersionRepl" +
      "y\022\017\n\007version\030\001 \001(\t\022\021\n\tbuildDate\030\002 \001(\t\022\021\n" +
      "\tgitCommit\030\003 \001(\t\022\021\n\tgitBranch\030\004 \001(\t\022\022\n\ng" +
      "itSummary\030\005 \001(\t2m\n\nServiceAPI\022*\n\004Ping\022\020." +
      "api.PingRequest\032\016.api.PingReply\"\000\0223\n\007Ver" +
      "sion\022\023.api.VersionRequest\032\021.api.VersionR" +
      "eply\"\000B$\n\022hxgm30.dice.pb.apiB\014DiceAPIPro" +
      "toP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_api_PingRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_api_PingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_PingRequest_descriptor,
        new java.lang.String[] { "Data", });
    internal_static_api_PingReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_api_PingReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_PingReply_descriptor,
        new java.lang.String[] { "Data", });
    internal_static_api_VersionRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_api_VersionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_VersionRequest_descriptor,
        new java.lang.String[] { "Data", });
    internal_static_api_VersionReply_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_api_VersionReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_VersionReply_descriptor,
        new java.lang.String[] { "Version", "BuildDate", "GitCommit", "GitBranch", "GitSummary", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
