// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dice.proto

package hxgm30.dice.pb.api;

public interface DiceVariousRollsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.DiceVariousRolls)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .api.DiceRepeatedRolls results = 1;</code>
   */
  java.util.List<hxgm30.dice.pb.api.DiceRepeatedRolls> 
      getResultsList();
  /**
   * <code>repeated .api.DiceRepeatedRolls results = 1;</code>
   */
  hxgm30.dice.pb.api.DiceRepeatedRolls getResults(int index);
  /**
   * <code>repeated .api.DiceRepeatedRolls results = 1;</code>
   */
  int getResultsCount();
  /**
   * <code>repeated .api.DiceRepeatedRolls results = 1;</code>
   */
  java.util.List<? extends hxgm30.dice.pb.api.DiceRepeatedRollsOrBuilder> 
      getResultsOrBuilderList();
  /**
   * <code>repeated .api.DiceRepeatedRolls results = 1;</code>
   */
  hxgm30.dice.pb.api.DiceRepeatedRollsOrBuilder getResultsOrBuilder(
      int index);
}
