// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dice.proto

package hxgm30.dice.pb.api;

/**
 * <pre>
 * DiceRollStats
 * </pre>
 *
 * Protobuf type {@code api.DiceRollStats}
 */
public  final class DiceRollStats extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:api.DiceRollStats)
    DiceRollStatsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DiceRollStats.newBuilder() to construct.
  private DiceRollStats(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DiceRollStats() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new DiceRollStats();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private DiceRollStats(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 13: {

            average_ = input.readFloat();
            break;
          }
          case 16: {

            high_ = input.readInt32();
            break;
          }
          case 24: {

            low_ = input.readInt32();
            break;
          }
          case 32: {

            sum_ = input.readInt32();
            break;
          }
          case 40: {

            count_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return hxgm30.dice.pb.api.DiceAPIProto.internal_static_api_DiceRollStats_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return hxgm30.dice.pb.api.DiceAPIProto.internal_static_api_DiceRollStats_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            hxgm30.dice.pb.api.DiceRollStats.class, hxgm30.dice.pb.api.DiceRollStats.Builder.class);
  }

  public static final int AVERAGE_FIELD_NUMBER = 1;
  private float average_;
  /**
   * <code>float average = 1;</code>
   * @return The average.
   */
  public float getAverage() {
    return average_;
  }

  public static final int COUNT_FIELD_NUMBER = 5;
  private int count_;
  /**
   * <code>int32 count = 5;</code>
   * @return The count.
   */
  public int getCount() {
    return count_;
  }

  public static final int HIGH_FIELD_NUMBER = 2;
  private int high_;
  /**
   * <code>int32 high = 2;</code>
   * @return The high.
   */
  public int getHigh() {
    return high_;
  }

  public static final int LOW_FIELD_NUMBER = 3;
  private int low_;
  /**
   * <code>int32 low = 3;</code>
   * @return The low.
   */
  public int getLow() {
    return low_;
  }

  public static final int SUM_FIELD_NUMBER = 4;
  private int sum_;
  /**
   * <code>int32 sum = 4;</code>
   * @return The sum.
   */
  public int getSum() {
    return sum_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (average_ != 0F) {
      output.writeFloat(1, average_);
    }
    if (high_ != 0) {
      output.writeInt32(2, high_);
    }
    if (low_ != 0) {
      output.writeInt32(3, low_);
    }
    if (sum_ != 0) {
      output.writeInt32(4, sum_);
    }
    if (count_ != 0) {
      output.writeInt32(5, count_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (average_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(1, average_);
    }
    if (high_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, high_);
    }
    if (low_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, low_);
    }
    if (sum_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, sum_);
    }
    if (count_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, count_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof hxgm30.dice.pb.api.DiceRollStats)) {
      return super.equals(obj);
    }
    hxgm30.dice.pb.api.DiceRollStats other = (hxgm30.dice.pb.api.DiceRollStats) obj;

    if (java.lang.Float.floatToIntBits(getAverage())
        != java.lang.Float.floatToIntBits(
            other.getAverage())) return false;
    if (getCount()
        != other.getCount()) return false;
    if (getHigh()
        != other.getHigh()) return false;
    if (getLow()
        != other.getLow()) return false;
    if (getSum()
        != other.getSum()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + AVERAGE_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getAverage());
    hash = (37 * hash) + COUNT_FIELD_NUMBER;
    hash = (53 * hash) + getCount();
    hash = (37 * hash) + HIGH_FIELD_NUMBER;
    hash = (53 * hash) + getHigh();
    hash = (37 * hash) + LOW_FIELD_NUMBER;
    hash = (53 * hash) + getLow();
    hash = (37 * hash) + SUM_FIELD_NUMBER;
    hash = (53 * hash) + getSum();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static hxgm30.dice.pb.api.DiceRollStats parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static hxgm30.dice.pb.api.DiceRollStats parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static hxgm30.dice.pb.api.DiceRollStats parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static hxgm30.dice.pb.api.DiceRollStats parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static hxgm30.dice.pb.api.DiceRollStats parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static hxgm30.dice.pb.api.DiceRollStats parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static hxgm30.dice.pb.api.DiceRollStats parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static hxgm30.dice.pb.api.DiceRollStats parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static hxgm30.dice.pb.api.DiceRollStats parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static hxgm30.dice.pb.api.DiceRollStats parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static hxgm30.dice.pb.api.DiceRollStats parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static hxgm30.dice.pb.api.DiceRollStats parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(hxgm30.dice.pb.api.DiceRollStats prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * DiceRollStats
   * </pre>
   *
   * Protobuf type {@code api.DiceRollStats}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:api.DiceRollStats)
      hxgm30.dice.pb.api.DiceRollStatsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return hxgm30.dice.pb.api.DiceAPIProto.internal_static_api_DiceRollStats_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return hxgm30.dice.pb.api.DiceAPIProto.internal_static_api_DiceRollStats_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              hxgm30.dice.pb.api.DiceRollStats.class, hxgm30.dice.pb.api.DiceRollStats.Builder.class);
    }

    // Construct using hxgm30.dice.pb.api.DiceRollStats.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      average_ = 0F;

      count_ = 0;

      high_ = 0;

      low_ = 0;

      sum_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return hxgm30.dice.pb.api.DiceAPIProto.internal_static_api_DiceRollStats_descriptor;
    }

    @java.lang.Override
    public hxgm30.dice.pb.api.DiceRollStats getDefaultInstanceForType() {
      return hxgm30.dice.pb.api.DiceRollStats.getDefaultInstance();
    }

    @java.lang.Override
    public hxgm30.dice.pb.api.DiceRollStats build() {
      hxgm30.dice.pb.api.DiceRollStats result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public hxgm30.dice.pb.api.DiceRollStats buildPartial() {
      hxgm30.dice.pb.api.DiceRollStats result = new hxgm30.dice.pb.api.DiceRollStats(this);
      result.average_ = average_;
      result.count_ = count_;
      result.high_ = high_;
      result.low_ = low_;
      result.sum_ = sum_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof hxgm30.dice.pb.api.DiceRollStats) {
        return mergeFrom((hxgm30.dice.pb.api.DiceRollStats)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(hxgm30.dice.pb.api.DiceRollStats other) {
      if (other == hxgm30.dice.pb.api.DiceRollStats.getDefaultInstance()) return this;
      if (other.getAverage() != 0F) {
        setAverage(other.getAverage());
      }
      if (other.getCount() != 0) {
        setCount(other.getCount());
      }
      if (other.getHigh() != 0) {
        setHigh(other.getHigh());
      }
      if (other.getLow() != 0) {
        setLow(other.getLow());
      }
      if (other.getSum() != 0) {
        setSum(other.getSum());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      hxgm30.dice.pb.api.DiceRollStats parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (hxgm30.dice.pb.api.DiceRollStats) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private float average_ ;
    /**
     * <code>float average = 1;</code>
     * @return The average.
     */
    public float getAverage() {
      return average_;
    }
    /**
     * <code>float average = 1;</code>
     * @param value The average to set.
     * @return This builder for chaining.
     */
    public Builder setAverage(float value) {
      
      average_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float average = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAverage() {
      
      average_ = 0F;
      onChanged();
      return this;
    }

    private int count_ ;
    /**
     * <code>int32 count = 5;</code>
     * @return The count.
     */
    public int getCount() {
      return count_;
    }
    /**
     * <code>int32 count = 5;</code>
     * @param value The count to set.
     * @return This builder for chaining.
     */
    public Builder setCount(int value) {
      
      count_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 count = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearCount() {
      
      count_ = 0;
      onChanged();
      return this;
    }

    private int high_ ;
    /**
     * <code>int32 high = 2;</code>
     * @return The high.
     */
    public int getHigh() {
      return high_;
    }
    /**
     * <code>int32 high = 2;</code>
     * @param value The high to set.
     * @return This builder for chaining.
     */
    public Builder setHigh(int value) {
      
      high_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 high = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearHigh() {
      
      high_ = 0;
      onChanged();
      return this;
    }

    private int low_ ;
    /**
     * <code>int32 low = 3;</code>
     * @return The low.
     */
    public int getLow() {
      return low_;
    }
    /**
     * <code>int32 low = 3;</code>
     * @param value The low to set.
     * @return This builder for chaining.
     */
    public Builder setLow(int value) {
      
      low_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 low = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearLow() {
      
      low_ = 0;
      onChanged();
      return this;
    }

    private int sum_ ;
    /**
     * <code>int32 sum = 4;</code>
     * @return The sum.
     */
    public int getSum() {
      return sum_;
    }
    /**
     * <code>int32 sum = 4;</code>
     * @param value The sum to set.
     * @return This builder for chaining.
     */
    public Builder setSum(int value) {
      
      sum_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 sum = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearSum() {
      
      sum_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:api.DiceRollStats)
  }

  // @@protoc_insertion_point(class_scope:api.DiceRollStats)
  private static final hxgm30.dice.pb.api.DiceRollStats DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new hxgm30.dice.pb.api.DiceRollStats();
  }

  public static hxgm30.dice.pb.api.DiceRollStats getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DiceRollStats>
      PARSER = new com.google.protobuf.AbstractParser<DiceRollStats>() {
    @java.lang.Override
    public DiceRollStats parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new DiceRollStats(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DiceRollStats> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DiceRollStats> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public hxgm30.dice.pb.api.DiceRollStats getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

