// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dice.proto

package hxgm30.dice.pb.api;

public interface DiceRollStatsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.DiceRollStats)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float average = 1;</code>
   * @return The average.
   */
  float getAverage();

  /**
   * <code>int32 count = 5;</code>
   * @return The count.
   */
  int getCount();

  /**
   * <code>int32 high = 2;</code>
   * @return The high.
   */
  int getHigh();

  /**
   * <code>int32 low = 3;</code>
   * @return The low.
   */
  int getLow();

  /**
   * <code>int32 sum = 4;</code>
   * @return The sum.
   */
  int getSum();
}
