// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dice.proto

package hxgm30.dice.pb.api;

/**
 * <pre>
 * MetaRoll
 * </pre>
 *
 * Protobuf type {@code api.MetaRoll}
 */
public  final class MetaRoll extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:api.MetaRoll)
    MetaRollOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MetaRoll.newBuilder() to construct.
  private MetaRoll(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MetaRoll() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new MetaRoll();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MetaRoll(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            hxgm30.dice.pb.api.DiceRoll.Builder subBuilder = null;
            if (roll_ != null) {
              subBuilder = roll_.toBuilder();
            }
            roll_ = input.readMessage(hxgm30.dice.pb.api.DiceRoll.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(roll_);
              roll_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            hxgm30.dice.pb.api.DiceRolls.Builder subBuilder = null;
            if (rolls_ != null) {
              subBuilder = rolls_.toBuilder();
            }
            rolls_ = input.readMessage(hxgm30.dice.pb.api.DiceRolls.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(rolls_);
              rolls_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            hxgm30.dice.pb.api.DiceRollStats.Builder subBuilder = null;
            if (stats_ != null) {
              subBuilder = stats_.toBuilder();
            }
            stats_ = input.readMessage(hxgm30.dice.pb.api.DiceRollStats.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(stats_);
              stats_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return hxgm30.dice.pb.api.DiceAPIProto.internal_static_api_MetaRoll_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return hxgm30.dice.pb.api.DiceAPIProto.internal_static_api_MetaRoll_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            hxgm30.dice.pb.api.MetaRoll.class, hxgm30.dice.pb.api.MetaRoll.Builder.class);
  }

  public static final int ROLL_FIELD_NUMBER = 1;
  private hxgm30.dice.pb.api.DiceRoll roll_;
  /**
   * <code>.api.DiceRoll roll = 1;</code>
   * @return Whether the roll field is set.
   */
  public boolean hasRoll() {
    return roll_ != null;
  }
  /**
   * <code>.api.DiceRoll roll = 1;</code>
   * @return The roll.
   */
  public hxgm30.dice.pb.api.DiceRoll getRoll() {
    return roll_ == null ? hxgm30.dice.pb.api.DiceRoll.getDefaultInstance() : roll_;
  }
  /**
   * <code>.api.DiceRoll roll = 1;</code>
   */
  public hxgm30.dice.pb.api.DiceRollOrBuilder getRollOrBuilder() {
    return getRoll();
  }

  public static final int ROLLS_FIELD_NUMBER = 2;
  private hxgm30.dice.pb.api.DiceRolls rolls_;
  /**
   * <code>.api.DiceRolls rolls = 2;</code>
   * @return Whether the rolls field is set.
   */
  public boolean hasRolls() {
    return rolls_ != null;
  }
  /**
   * <code>.api.DiceRolls rolls = 2;</code>
   * @return The rolls.
   */
  public hxgm30.dice.pb.api.DiceRolls getRolls() {
    return rolls_ == null ? hxgm30.dice.pb.api.DiceRolls.getDefaultInstance() : rolls_;
  }
  /**
   * <code>.api.DiceRolls rolls = 2;</code>
   */
  public hxgm30.dice.pb.api.DiceRollsOrBuilder getRollsOrBuilder() {
    return getRolls();
  }

  public static final int STATS_FIELD_NUMBER = 3;
  private hxgm30.dice.pb.api.DiceRollStats stats_;
  /**
   * <code>.api.DiceRollStats stats = 3;</code>
   * @return Whether the stats field is set.
   */
  public boolean hasStats() {
    return stats_ != null;
  }
  /**
   * <code>.api.DiceRollStats stats = 3;</code>
   * @return The stats.
   */
  public hxgm30.dice.pb.api.DiceRollStats getStats() {
    return stats_ == null ? hxgm30.dice.pb.api.DiceRollStats.getDefaultInstance() : stats_;
  }
  /**
   * <code>.api.DiceRollStats stats = 3;</code>
   */
  public hxgm30.dice.pb.api.DiceRollStatsOrBuilder getStatsOrBuilder() {
    return getStats();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (roll_ != null) {
      output.writeMessage(1, getRoll());
    }
    if (rolls_ != null) {
      output.writeMessage(2, getRolls());
    }
    if (stats_ != null) {
      output.writeMessage(3, getStats());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (roll_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getRoll());
    }
    if (rolls_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getRolls());
    }
    if (stats_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getStats());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof hxgm30.dice.pb.api.MetaRoll)) {
      return super.equals(obj);
    }
    hxgm30.dice.pb.api.MetaRoll other = (hxgm30.dice.pb.api.MetaRoll) obj;

    if (hasRoll() != other.hasRoll()) return false;
    if (hasRoll()) {
      if (!getRoll()
          .equals(other.getRoll())) return false;
    }
    if (hasRolls() != other.hasRolls()) return false;
    if (hasRolls()) {
      if (!getRolls()
          .equals(other.getRolls())) return false;
    }
    if (hasStats() != other.hasStats()) return false;
    if (hasStats()) {
      if (!getStats()
          .equals(other.getStats())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasRoll()) {
      hash = (37 * hash) + ROLL_FIELD_NUMBER;
      hash = (53 * hash) + getRoll().hashCode();
    }
    if (hasRolls()) {
      hash = (37 * hash) + ROLLS_FIELD_NUMBER;
      hash = (53 * hash) + getRolls().hashCode();
    }
    if (hasStats()) {
      hash = (37 * hash) + STATS_FIELD_NUMBER;
      hash = (53 * hash) + getStats().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static hxgm30.dice.pb.api.MetaRoll parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static hxgm30.dice.pb.api.MetaRoll parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static hxgm30.dice.pb.api.MetaRoll parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static hxgm30.dice.pb.api.MetaRoll parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static hxgm30.dice.pb.api.MetaRoll parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static hxgm30.dice.pb.api.MetaRoll parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static hxgm30.dice.pb.api.MetaRoll parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static hxgm30.dice.pb.api.MetaRoll parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static hxgm30.dice.pb.api.MetaRoll parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static hxgm30.dice.pb.api.MetaRoll parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static hxgm30.dice.pb.api.MetaRoll parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static hxgm30.dice.pb.api.MetaRoll parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(hxgm30.dice.pb.api.MetaRoll prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * MetaRoll
   * </pre>
   *
   * Protobuf type {@code api.MetaRoll}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:api.MetaRoll)
      hxgm30.dice.pb.api.MetaRollOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return hxgm30.dice.pb.api.DiceAPIProto.internal_static_api_MetaRoll_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return hxgm30.dice.pb.api.DiceAPIProto.internal_static_api_MetaRoll_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              hxgm30.dice.pb.api.MetaRoll.class, hxgm30.dice.pb.api.MetaRoll.Builder.class);
    }

    // Construct using hxgm30.dice.pb.api.MetaRoll.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (rollBuilder_ == null) {
        roll_ = null;
      } else {
        roll_ = null;
        rollBuilder_ = null;
      }
      if (rollsBuilder_ == null) {
        rolls_ = null;
      } else {
        rolls_ = null;
        rollsBuilder_ = null;
      }
      if (statsBuilder_ == null) {
        stats_ = null;
      } else {
        stats_ = null;
        statsBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return hxgm30.dice.pb.api.DiceAPIProto.internal_static_api_MetaRoll_descriptor;
    }

    @java.lang.Override
    public hxgm30.dice.pb.api.MetaRoll getDefaultInstanceForType() {
      return hxgm30.dice.pb.api.MetaRoll.getDefaultInstance();
    }

    @java.lang.Override
    public hxgm30.dice.pb.api.MetaRoll build() {
      hxgm30.dice.pb.api.MetaRoll result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public hxgm30.dice.pb.api.MetaRoll buildPartial() {
      hxgm30.dice.pb.api.MetaRoll result = new hxgm30.dice.pb.api.MetaRoll(this);
      if (rollBuilder_ == null) {
        result.roll_ = roll_;
      } else {
        result.roll_ = rollBuilder_.build();
      }
      if (rollsBuilder_ == null) {
        result.rolls_ = rolls_;
      } else {
        result.rolls_ = rollsBuilder_.build();
      }
      if (statsBuilder_ == null) {
        result.stats_ = stats_;
      } else {
        result.stats_ = statsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof hxgm30.dice.pb.api.MetaRoll) {
        return mergeFrom((hxgm30.dice.pb.api.MetaRoll)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(hxgm30.dice.pb.api.MetaRoll other) {
      if (other == hxgm30.dice.pb.api.MetaRoll.getDefaultInstance()) return this;
      if (other.hasRoll()) {
        mergeRoll(other.getRoll());
      }
      if (other.hasRolls()) {
        mergeRolls(other.getRolls());
      }
      if (other.hasStats()) {
        mergeStats(other.getStats());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      hxgm30.dice.pb.api.MetaRoll parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (hxgm30.dice.pb.api.MetaRoll) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private hxgm30.dice.pb.api.DiceRoll roll_;
    private com.google.protobuf.SingleFieldBuilderV3<
        hxgm30.dice.pb.api.DiceRoll, hxgm30.dice.pb.api.DiceRoll.Builder, hxgm30.dice.pb.api.DiceRollOrBuilder> rollBuilder_;
    /**
     * <code>.api.DiceRoll roll = 1;</code>
     * @return Whether the roll field is set.
     */
    public boolean hasRoll() {
      return rollBuilder_ != null || roll_ != null;
    }
    /**
     * <code>.api.DiceRoll roll = 1;</code>
     * @return The roll.
     */
    public hxgm30.dice.pb.api.DiceRoll getRoll() {
      if (rollBuilder_ == null) {
        return roll_ == null ? hxgm30.dice.pb.api.DiceRoll.getDefaultInstance() : roll_;
      } else {
        return rollBuilder_.getMessage();
      }
    }
    /**
     * <code>.api.DiceRoll roll = 1;</code>
     */
    public Builder setRoll(hxgm30.dice.pb.api.DiceRoll value) {
      if (rollBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        roll_ = value;
        onChanged();
      } else {
        rollBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.api.DiceRoll roll = 1;</code>
     */
    public Builder setRoll(
        hxgm30.dice.pb.api.DiceRoll.Builder builderForValue) {
      if (rollBuilder_ == null) {
        roll_ = builderForValue.build();
        onChanged();
      } else {
        rollBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.api.DiceRoll roll = 1;</code>
     */
    public Builder mergeRoll(hxgm30.dice.pb.api.DiceRoll value) {
      if (rollBuilder_ == null) {
        if (roll_ != null) {
          roll_ =
            hxgm30.dice.pb.api.DiceRoll.newBuilder(roll_).mergeFrom(value).buildPartial();
        } else {
          roll_ = value;
        }
        onChanged();
      } else {
        rollBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.api.DiceRoll roll = 1;</code>
     */
    public Builder clearRoll() {
      if (rollBuilder_ == null) {
        roll_ = null;
        onChanged();
      } else {
        roll_ = null;
        rollBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.api.DiceRoll roll = 1;</code>
     */
    public hxgm30.dice.pb.api.DiceRoll.Builder getRollBuilder() {
      
      onChanged();
      return getRollFieldBuilder().getBuilder();
    }
    /**
     * <code>.api.DiceRoll roll = 1;</code>
     */
    public hxgm30.dice.pb.api.DiceRollOrBuilder getRollOrBuilder() {
      if (rollBuilder_ != null) {
        return rollBuilder_.getMessageOrBuilder();
      } else {
        return roll_ == null ?
            hxgm30.dice.pb.api.DiceRoll.getDefaultInstance() : roll_;
      }
    }
    /**
     * <code>.api.DiceRoll roll = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        hxgm30.dice.pb.api.DiceRoll, hxgm30.dice.pb.api.DiceRoll.Builder, hxgm30.dice.pb.api.DiceRollOrBuilder> 
        getRollFieldBuilder() {
      if (rollBuilder_ == null) {
        rollBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            hxgm30.dice.pb.api.DiceRoll, hxgm30.dice.pb.api.DiceRoll.Builder, hxgm30.dice.pb.api.DiceRollOrBuilder>(
                getRoll(),
                getParentForChildren(),
                isClean());
        roll_ = null;
      }
      return rollBuilder_;
    }

    private hxgm30.dice.pb.api.DiceRolls rolls_;
    private com.google.protobuf.SingleFieldBuilderV3<
        hxgm30.dice.pb.api.DiceRolls, hxgm30.dice.pb.api.DiceRolls.Builder, hxgm30.dice.pb.api.DiceRollsOrBuilder> rollsBuilder_;
    /**
     * <code>.api.DiceRolls rolls = 2;</code>
     * @return Whether the rolls field is set.
     */
    public boolean hasRolls() {
      return rollsBuilder_ != null || rolls_ != null;
    }
    /**
     * <code>.api.DiceRolls rolls = 2;</code>
     * @return The rolls.
     */
    public hxgm30.dice.pb.api.DiceRolls getRolls() {
      if (rollsBuilder_ == null) {
        return rolls_ == null ? hxgm30.dice.pb.api.DiceRolls.getDefaultInstance() : rolls_;
      } else {
        return rollsBuilder_.getMessage();
      }
    }
    /**
     * <code>.api.DiceRolls rolls = 2;</code>
     */
    public Builder setRolls(hxgm30.dice.pb.api.DiceRolls value) {
      if (rollsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        rolls_ = value;
        onChanged();
      } else {
        rollsBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.api.DiceRolls rolls = 2;</code>
     */
    public Builder setRolls(
        hxgm30.dice.pb.api.DiceRolls.Builder builderForValue) {
      if (rollsBuilder_ == null) {
        rolls_ = builderForValue.build();
        onChanged();
      } else {
        rollsBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.api.DiceRolls rolls = 2;</code>
     */
    public Builder mergeRolls(hxgm30.dice.pb.api.DiceRolls value) {
      if (rollsBuilder_ == null) {
        if (rolls_ != null) {
          rolls_ =
            hxgm30.dice.pb.api.DiceRolls.newBuilder(rolls_).mergeFrom(value).buildPartial();
        } else {
          rolls_ = value;
        }
        onChanged();
      } else {
        rollsBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.api.DiceRolls rolls = 2;</code>
     */
    public Builder clearRolls() {
      if (rollsBuilder_ == null) {
        rolls_ = null;
        onChanged();
      } else {
        rolls_ = null;
        rollsBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.api.DiceRolls rolls = 2;</code>
     */
    public hxgm30.dice.pb.api.DiceRolls.Builder getRollsBuilder() {
      
      onChanged();
      return getRollsFieldBuilder().getBuilder();
    }
    /**
     * <code>.api.DiceRolls rolls = 2;</code>
     */
    public hxgm30.dice.pb.api.DiceRollsOrBuilder getRollsOrBuilder() {
      if (rollsBuilder_ != null) {
        return rollsBuilder_.getMessageOrBuilder();
      } else {
        return rolls_ == null ?
            hxgm30.dice.pb.api.DiceRolls.getDefaultInstance() : rolls_;
      }
    }
    /**
     * <code>.api.DiceRolls rolls = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        hxgm30.dice.pb.api.DiceRolls, hxgm30.dice.pb.api.DiceRolls.Builder, hxgm30.dice.pb.api.DiceRollsOrBuilder> 
        getRollsFieldBuilder() {
      if (rollsBuilder_ == null) {
        rollsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            hxgm30.dice.pb.api.DiceRolls, hxgm30.dice.pb.api.DiceRolls.Builder, hxgm30.dice.pb.api.DiceRollsOrBuilder>(
                getRolls(),
                getParentForChildren(),
                isClean());
        rolls_ = null;
      }
      return rollsBuilder_;
    }

    private hxgm30.dice.pb.api.DiceRollStats stats_;
    private com.google.protobuf.SingleFieldBuilderV3<
        hxgm30.dice.pb.api.DiceRollStats, hxgm30.dice.pb.api.DiceRollStats.Builder, hxgm30.dice.pb.api.DiceRollStatsOrBuilder> statsBuilder_;
    /**
     * <code>.api.DiceRollStats stats = 3;</code>
     * @return Whether the stats field is set.
     */
    public boolean hasStats() {
      return statsBuilder_ != null || stats_ != null;
    }
    /**
     * <code>.api.DiceRollStats stats = 3;</code>
     * @return The stats.
     */
    public hxgm30.dice.pb.api.DiceRollStats getStats() {
      if (statsBuilder_ == null) {
        return stats_ == null ? hxgm30.dice.pb.api.DiceRollStats.getDefaultInstance() : stats_;
      } else {
        return statsBuilder_.getMessage();
      }
    }
    /**
     * <code>.api.DiceRollStats stats = 3;</code>
     */
    public Builder setStats(hxgm30.dice.pb.api.DiceRollStats value) {
      if (statsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        stats_ = value;
        onChanged();
      } else {
        statsBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.api.DiceRollStats stats = 3;</code>
     */
    public Builder setStats(
        hxgm30.dice.pb.api.DiceRollStats.Builder builderForValue) {
      if (statsBuilder_ == null) {
        stats_ = builderForValue.build();
        onChanged();
      } else {
        statsBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.api.DiceRollStats stats = 3;</code>
     */
    public Builder mergeStats(hxgm30.dice.pb.api.DiceRollStats value) {
      if (statsBuilder_ == null) {
        if (stats_ != null) {
          stats_ =
            hxgm30.dice.pb.api.DiceRollStats.newBuilder(stats_).mergeFrom(value).buildPartial();
        } else {
          stats_ = value;
        }
        onChanged();
      } else {
        statsBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.api.DiceRollStats stats = 3;</code>
     */
    public Builder clearStats() {
      if (statsBuilder_ == null) {
        stats_ = null;
        onChanged();
      } else {
        stats_ = null;
        statsBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.api.DiceRollStats stats = 3;</code>
     */
    public hxgm30.dice.pb.api.DiceRollStats.Builder getStatsBuilder() {
      
      onChanged();
      return getStatsFieldBuilder().getBuilder();
    }
    /**
     * <code>.api.DiceRollStats stats = 3;</code>
     */
    public hxgm30.dice.pb.api.DiceRollStatsOrBuilder getStatsOrBuilder() {
      if (statsBuilder_ != null) {
        return statsBuilder_.getMessageOrBuilder();
      } else {
        return stats_ == null ?
            hxgm30.dice.pb.api.DiceRollStats.getDefaultInstance() : stats_;
      }
    }
    /**
     * <code>.api.DiceRollStats stats = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        hxgm30.dice.pb.api.DiceRollStats, hxgm30.dice.pb.api.DiceRollStats.Builder, hxgm30.dice.pb.api.DiceRollStatsOrBuilder> 
        getStatsFieldBuilder() {
      if (statsBuilder_ == null) {
        statsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            hxgm30.dice.pb.api.DiceRollStats, hxgm30.dice.pb.api.DiceRollStats.Builder, hxgm30.dice.pb.api.DiceRollStatsOrBuilder>(
                getStats(),
                getParentForChildren(),
                isClean());
        stats_ = null;
      }
      return statsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:api.MetaRoll)
  }

  // @@protoc_insertion_point(class_scope:api.MetaRoll)
  private static final hxgm30.dice.pb.api.MetaRoll DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new hxgm30.dice.pb.api.MetaRoll();
  }

  public static hxgm30.dice.pb.api.MetaRoll getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MetaRoll>
      PARSER = new com.google.protobuf.AbstractParser<MetaRoll>() {
    @java.lang.Override
    public MetaRoll parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MetaRoll(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MetaRoll> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MetaRoll> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public hxgm30.dice.pb.api.MetaRoll getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

