// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dice.proto

package hxgm30.dice.pb.api;

public interface MetaRollsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.MetaRolls)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .api.MetaRoll results = 1;</code>
   */
  java.util.List<hxgm30.dice.pb.api.MetaRoll> 
      getResultsList();
  /**
   * <code>repeated .api.MetaRoll results = 1;</code>
   */
  hxgm30.dice.pb.api.MetaRoll getResults(int index);
  /**
   * <code>repeated .api.MetaRoll results = 1;</code>
   */
  int getResultsCount();
  /**
   * <code>repeated .api.MetaRoll results = 1;</code>
   */
  java.util.List<? extends hxgm30.dice.pb.api.MetaRollOrBuilder> 
      getResultsOrBuilderList();
  /**
   * <code>repeated .api.MetaRoll results = 1;</code>
   */
  hxgm30.dice.pb.api.MetaRollOrBuilder getResultsOrBuilder(
      int index);
}
