// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dice.proto

package hxgm30.dice.pb.api;

public interface MetaRollOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.MetaRoll)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.api.DiceRoll roll = 1;</code>
   * @return Whether the roll field is set.
   */
  boolean hasRoll();
  /**
   * <code>.api.DiceRoll roll = 1;</code>
   * @return The roll.
   */
  hxgm30.dice.pb.api.DiceRoll getRoll();
  /**
   * <code>.api.DiceRoll roll = 1;</code>
   */
  hxgm30.dice.pb.api.DiceRollOrBuilder getRollOrBuilder();

  /**
   * <code>.api.DiceRolls rolls = 2;</code>
   * @return Whether the rolls field is set.
   */
  boolean hasRolls();
  /**
   * <code>.api.DiceRolls rolls = 2;</code>
   * @return The rolls.
   */
  hxgm30.dice.pb.api.DiceRolls getRolls();
  /**
   * <code>.api.DiceRolls rolls = 2;</code>
   */
  hxgm30.dice.pb.api.DiceRollsOrBuilder getRollsOrBuilder();

  /**
   * <code>.api.DiceRollStats stats = 3;</code>
   * @return Whether the stats field is set.
   */
  boolean hasStats();
  /**
   * <code>.api.DiceRollStats stats = 3;</code>
   * @return The stats.
   */
  hxgm30.dice.pb.api.DiceRollStats getStats();
  /**
   * <code>.api.DiceRollStats stats = 3;</code>
   */
  hxgm30.dice.pb.api.DiceRollStatsOrBuilder getStatsOrBuilder();
}
