// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dice.proto

package hxgm30.dice.pb.api;

public interface PingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.PingRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string data = 1;</code>
   * @return The data.
   */
  java.lang.String getData();
  /**
   * <code>string data = 1;</code>
   * @return The bytes for data.
   */
  com.google.protobuf.ByteString
      getDataBytes();
}
