// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dice.proto

package hxgm30.dice.pb.api;

public interface RollVariousRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.RollVariousRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .api.RollsRequest rolls = 1;</code>
   */
  java.util.List<hxgm30.dice.pb.api.RollsRequest> 
      getRollsList();
  /**
   * <code>repeated .api.RollsRequest rolls = 1;</code>
   */
  hxgm30.dice.pb.api.RollsRequest getRolls(int index);
  /**
   * <code>repeated .api.RollsRequest rolls = 1;</code>
   */
  int getRollsCount();
  /**
   * <code>repeated .api.RollsRequest rolls = 1;</code>
   */
  java.util.List<? extends hxgm30.dice.pb.api.RollsRequestOrBuilder> 
      getRollsOrBuilderList();
  /**
   * <code>repeated .api.RollsRequest rolls = 1;</code>
   */
  hxgm30.dice.pb.api.RollsRequestOrBuilder getRollsOrBuilder(
      int index);
}
