// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dice.proto

package hxgm30.dice.pb.api;

public interface RollsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.RollsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string diceType = 1;</code>
   * @return The diceType.
   */
  java.lang.String getDiceType();
  /**
   * <code>string diceType = 1;</code>
   * @return The bytes for diceType.
   */
  com.google.protobuf.ByteString
      getDiceTypeBytes();

  /**
   * <code>int32 rollCount = 2;</code>
   * @return The rollCount.
   */
  int getRollCount();
}
