// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dice.proto

package hxgm30.dice.pb.api;

public interface RollRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.RollRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string diceType = 1;</code>
   * @return The diceType.
   */
  java.lang.String getDiceType();
  /**
   * <code>string diceType = 1;</code>
   * @return The bytes for diceType.
   */
  com.google.protobuf.ByteString
      getDiceTypeBytes();
}
