// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dice.proto

package hxgm30.dice.pb.api;

/**
 * <pre>
 * RollVariousRequest
 * </pre>
 *
 * Protobuf type {@code api.RollVariousRequest}
 */
public  final class RollVariousRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:api.RollVariousRequest)
    RollVariousRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RollVariousRequest.newBuilder() to construct.
  private RollVariousRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RollVariousRequest() {
    rolls_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RollVariousRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RollVariousRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              rolls_ = new java.util.ArrayList<hxgm30.dice.pb.api.RollsRequest>();
              mutable_bitField0_ |= 0x00000001;
            }
            rolls_.add(
                input.readMessage(hxgm30.dice.pb.api.RollsRequest.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        rolls_ = java.util.Collections.unmodifiableList(rolls_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return hxgm30.dice.pb.api.DiceAPIProto.internal_static_api_RollVariousRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return hxgm30.dice.pb.api.DiceAPIProto.internal_static_api_RollVariousRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            hxgm30.dice.pb.api.RollVariousRequest.class, hxgm30.dice.pb.api.RollVariousRequest.Builder.class);
  }

  public static final int ROLLS_FIELD_NUMBER = 1;
  private java.util.List<hxgm30.dice.pb.api.RollsRequest> rolls_;
  /**
   * <code>repeated .api.RollsRequest rolls = 1;</code>
   */
  public java.util.List<hxgm30.dice.pb.api.RollsRequest> getRollsList() {
    return rolls_;
  }
  /**
   * <code>repeated .api.RollsRequest rolls = 1;</code>
   */
  public java.util.List<? extends hxgm30.dice.pb.api.RollsRequestOrBuilder> 
      getRollsOrBuilderList() {
    return rolls_;
  }
  /**
   * <code>repeated .api.RollsRequest rolls = 1;</code>
   */
  public int getRollsCount() {
    return rolls_.size();
  }
  /**
   * <code>repeated .api.RollsRequest rolls = 1;</code>
   */
  public hxgm30.dice.pb.api.RollsRequest getRolls(int index) {
    return rolls_.get(index);
  }
  /**
   * <code>repeated .api.RollsRequest rolls = 1;</code>
   */
  public hxgm30.dice.pb.api.RollsRequestOrBuilder getRollsOrBuilder(
      int index) {
    return rolls_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < rolls_.size(); i++) {
      output.writeMessage(1, rolls_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < rolls_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, rolls_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof hxgm30.dice.pb.api.RollVariousRequest)) {
      return super.equals(obj);
    }
    hxgm30.dice.pb.api.RollVariousRequest other = (hxgm30.dice.pb.api.RollVariousRequest) obj;

    if (!getRollsList()
        .equals(other.getRollsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getRollsCount() > 0) {
      hash = (37 * hash) + ROLLS_FIELD_NUMBER;
      hash = (53 * hash) + getRollsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static hxgm30.dice.pb.api.RollVariousRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static hxgm30.dice.pb.api.RollVariousRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static hxgm30.dice.pb.api.RollVariousRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static hxgm30.dice.pb.api.RollVariousRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static hxgm30.dice.pb.api.RollVariousRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static hxgm30.dice.pb.api.RollVariousRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static hxgm30.dice.pb.api.RollVariousRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static hxgm30.dice.pb.api.RollVariousRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static hxgm30.dice.pb.api.RollVariousRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static hxgm30.dice.pb.api.RollVariousRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static hxgm30.dice.pb.api.RollVariousRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static hxgm30.dice.pb.api.RollVariousRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(hxgm30.dice.pb.api.RollVariousRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * RollVariousRequest
   * </pre>
   *
   * Protobuf type {@code api.RollVariousRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:api.RollVariousRequest)
      hxgm30.dice.pb.api.RollVariousRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return hxgm30.dice.pb.api.DiceAPIProto.internal_static_api_RollVariousRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return hxgm30.dice.pb.api.DiceAPIProto.internal_static_api_RollVariousRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              hxgm30.dice.pb.api.RollVariousRequest.class, hxgm30.dice.pb.api.RollVariousRequest.Builder.class);
    }

    // Construct using hxgm30.dice.pb.api.RollVariousRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getRollsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (rollsBuilder_ == null) {
        rolls_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        rollsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return hxgm30.dice.pb.api.DiceAPIProto.internal_static_api_RollVariousRequest_descriptor;
    }

    @java.lang.Override
    public hxgm30.dice.pb.api.RollVariousRequest getDefaultInstanceForType() {
      return hxgm30.dice.pb.api.RollVariousRequest.getDefaultInstance();
    }

    @java.lang.Override
    public hxgm30.dice.pb.api.RollVariousRequest build() {
      hxgm30.dice.pb.api.RollVariousRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public hxgm30.dice.pb.api.RollVariousRequest buildPartial() {
      hxgm30.dice.pb.api.RollVariousRequest result = new hxgm30.dice.pb.api.RollVariousRequest(this);
      int from_bitField0_ = bitField0_;
      if (rollsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          rolls_ = java.util.Collections.unmodifiableList(rolls_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.rolls_ = rolls_;
      } else {
        result.rolls_ = rollsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof hxgm30.dice.pb.api.RollVariousRequest) {
        return mergeFrom((hxgm30.dice.pb.api.RollVariousRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(hxgm30.dice.pb.api.RollVariousRequest other) {
      if (other == hxgm30.dice.pb.api.RollVariousRequest.getDefaultInstance()) return this;
      if (rollsBuilder_ == null) {
        if (!other.rolls_.isEmpty()) {
          if (rolls_.isEmpty()) {
            rolls_ = other.rolls_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureRollsIsMutable();
            rolls_.addAll(other.rolls_);
          }
          onChanged();
        }
      } else {
        if (!other.rolls_.isEmpty()) {
          if (rollsBuilder_.isEmpty()) {
            rollsBuilder_.dispose();
            rollsBuilder_ = null;
            rolls_ = other.rolls_;
            bitField0_ = (bitField0_ & ~0x00000001);
            rollsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getRollsFieldBuilder() : null;
          } else {
            rollsBuilder_.addAllMessages(other.rolls_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      hxgm30.dice.pb.api.RollVariousRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (hxgm30.dice.pb.api.RollVariousRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<hxgm30.dice.pb.api.RollsRequest> rolls_ =
      java.util.Collections.emptyList();
    private void ensureRollsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        rolls_ = new java.util.ArrayList<hxgm30.dice.pb.api.RollsRequest>(rolls_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        hxgm30.dice.pb.api.RollsRequest, hxgm30.dice.pb.api.RollsRequest.Builder, hxgm30.dice.pb.api.RollsRequestOrBuilder> rollsBuilder_;

    /**
     * <code>repeated .api.RollsRequest rolls = 1;</code>
     */
    public java.util.List<hxgm30.dice.pb.api.RollsRequest> getRollsList() {
      if (rollsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(rolls_);
      } else {
        return rollsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .api.RollsRequest rolls = 1;</code>
     */
    public int getRollsCount() {
      if (rollsBuilder_ == null) {
        return rolls_.size();
      } else {
        return rollsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .api.RollsRequest rolls = 1;</code>
     */
    public hxgm30.dice.pb.api.RollsRequest getRolls(int index) {
      if (rollsBuilder_ == null) {
        return rolls_.get(index);
      } else {
        return rollsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .api.RollsRequest rolls = 1;</code>
     */
    public Builder setRolls(
        int index, hxgm30.dice.pb.api.RollsRequest value) {
      if (rollsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRollsIsMutable();
        rolls_.set(index, value);
        onChanged();
      } else {
        rollsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .api.RollsRequest rolls = 1;</code>
     */
    public Builder setRolls(
        int index, hxgm30.dice.pb.api.RollsRequest.Builder builderForValue) {
      if (rollsBuilder_ == null) {
        ensureRollsIsMutable();
        rolls_.set(index, builderForValue.build());
        onChanged();
      } else {
        rollsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .api.RollsRequest rolls = 1;</code>
     */
    public Builder addRolls(hxgm30.dice.pb.api.RollsRequest value) {
      if (rollsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRollsIsMutable();
        rolls_.add(value);
        onChanged();
      } else {
        rollsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .api.RollsRequest rolls = 1;</code>
     */
    public Builder addRolls(
        int index, hxgm30.dice.pb.api.RollsRequest value) {
      if (rollsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRollsIsMutable();
        rolls_.add(index, value);
        onChanged();
      } else {
        rollsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .api.RollsRequest rolls = 1;</code>
     */
    public Builder addRolls(
        hxgm30.dice.pb.api.RollsRequest.Builder builderForValue) {
      if (rollsBuilder_ == null) {
        ensureRollsIsMutable();
        rolls_.add(builderForValue.build());
        onChanged();
      } else {
        rollsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .api.RollsRequest rolls = 1;</code>
     */
    public Builder addRolls(
        int index, hxgm30.dice.pb.api.RollsRequest.Builder builderForValue) {
      if (rollsBuilder_ == null) {
        ensureRollsIsMutable();
        rolls_.add(index, builderForValue.build());
        onChanged();
      } else {
        rollsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .api.RollsRequest rolls = 1;</code>
     */
    public Builder addAllRolls(
        java.lang.Iterable<? extends hxgm30.dice.pb.api.RollsRequest> values) {
      if (rollsBuilder_ == null) {
        ensureRollsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, rolls_);
        onChanged();
      } else {
        rollsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .api.RollsRequest rolls = 1;</code>
     */
    public Builder clearRolls() {
      if (rollsBuilder_ == null) {
        rolls_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        rollsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .api.RollsRequest rolls = 1;</code>
     */
    public Builder removeRolls(int index) {
      if (rollsBuilder_ == null) {
        ensureRollsIsMutable();
        rolls_.remove(index);
        onChanged();
      } else {
        rollsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .api.RollsRequest rolls = 1;</code>
     */
    public hxgm30.dice.pb.api.RollsRequest.Builder getRollsBuilder(
        int index) {
      return getRollsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .api.RollsRequest rolls = 1;</code>
     */
    public hxgm30.dice.pb.api.RollsRequestOrBuilder getRollsOrBuilder(
        int index) {
      if (rollsBuilder_ == null) {
        return rolls_.get(index);  } else {
        return rollsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .api.RollsRequest rolls = 1;</code>
     */
    public java.util.List<? extends hxgm30.dice.pb.api.RollsRequestOrBuilder> 
         getRollsOrBuilderList() {
      if (rollsBuilder_ != null) {
        return rollsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(rolls_);
      }
    }
    /**
     * <code>repeated .api.RollsRequest rolls = 1;</code>
     */
    public hxgm30.dice.pb.api.RollsRequest.Builder addRollsBuilder() {
      return getRollsFieldBuilder().addBuilder(
          hxgm30.dice.pb.api.RollsRequest.getDefaultInstance());
    }
    /**
     * <code>repeated .api.RollsRequest rolls = 1;</code>
     */
    public hxgm30.dice.pb.api.RollsRequest.Builder addRollsBuilder(
        int index) {
      return getRollsFieldBuilder().addBuilder(
          index, hxgm30.dice.pb.api.RollsRequest.getDefaultInstance());
    }
    /**
     * <code>repeated .api.RollsRequest rolls = 1;</code>
     */
    public java.util.List<hxgm30.dice.pb.api.RollsRequest.Builder> 
         getRollsBuilderList() {
      return getRollsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        hxgm30.dice.pb.api.RollsRequest, hxgm30.dice.pb.api.RollsRequest.Builder, hxgm30.dice.pb.api.RollsRequestOrBuilder> 
        getRollsFieldBuilder() {
      if (rollsBuilder_ == null) {
        rollsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            hxgm30.dice.pb.api.RollsRequest, hxgm30.dice.pb.api.RollsRequest.Builder, hxgm30.dice.pb.api.RollsRequestOrBuilder>(
                rolls_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        rolls_ = null;
      }
      return rollsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:api.RollVariousRequest)
  }

  // @@protoc_insertion_point(class_scope:api.RollVariousRequest)
  private static final hxgm30.dice.pb.api.RollVariousRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new hxgm30.dice.pb.api.RollVariousRequest();
  }

  public static hxgm30.dice.pb.api.RollVariousRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RollVariousRequest>
      PARSER = new com.google.protobuf.AbstractParser<RollVariousRequest>() {
    @java.lang.Override
    public RollVariousRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RollVariousRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RollVariousRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RollVariousRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public hxgm30.dice.pb.api.RollVariousRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

