// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dice.proto

package hxgm30.dice.pb.api;

public interface VariousDiceRollsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.VariousDiceRolls)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .api.DiceRolls results = 1;</code>
   */
  java.util.List<hxgm30.dice.pb.api.DiceRolls> 
      getResultsList();
  /**
   * <code>repeated .api.DiceRolls results = 1;</code>
   */
  hxgm30.dice.pb.api.DiceRolls getResults(int index);
  /**
   * <code>repeated .api.DiceRolls results = 1;</code>
   */
  int getResultsCount();
  /**
   * <code>repeated .api.DiceRolls results = 1;</code>
   */
  java.util.List<? extends hxgm30.dice.pb.api.DiceRollsOrBuilder> 
      getResultsOrBuilderList();
  /**
   * <code>repeated .api.DiceRolls results = 1;</code>
   */
  hxgm30.dice.pb.api.DiceRollsOrBuilder getResultsOrBuilder(
      int index);
}
