// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dice.proto

package hxgm30.dice.pb.api;

public interface VersionReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.VersionReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string version = 1;</code>
   * @return The version.
   */
  java.lang.String getVersion();
  /**
   * <code>string version = 1;</code>
   * @return The bytes for version.
   */
  com.google.protobuf.ByteString
      getVersionBytes();

  /**
   * <code>string buildDate = 2;</code>
   * @return The buildDate.
   */
  java.lang.String getBuildDate();
  /**
   * <code>string buildDate = 2;</code>
   * @return The bytes for buildDate.
   */
  com.google.protobuf.ByteString
      getBuildDateBytes();

  /**
   * <code>string gitCommit = 3;</code>
   * @return The gitCommit.
   */
  java.lang.String getGitCommit();
  /**
   * <code>string gitCommit = 3;</code>
   * @return The bytes for gitCommit.
   */
  com.google.protobuf.ByteString
      getGitCommitBytes();

  /**
   * <code>string gitBranch = 4;</code>
   * @return The gitBranch.
   */
  java.lang.String getGitBranch();
  /**
   * <code>string gitBranch = 4;</code>
   * @return The bytes for gitBranch.
   */
  com.google.protobuf.ByteString
      getGitBranchBytes();

  /**
   * <code>string gitSummary = 5;</code>
   * @return The gitSummary.
   */
  java.lang.String getGitSummary();
  /**
   * <code>string gitSummary = 5;</code>
   * @return The bytes for gitSummary.
   */
  com.google.protobuf.ByteString
      getGitSummaryBytes();
}
